CELLSIZE = 50

BOARD_CELLS = 9
BOARD_SIZE = BOARD_CELLS * CELLSIZE

X_OFFSET = 175
Y_OFFSET = 65

X_ARROW_OFFSET = X_OFFSET + 10
Y_ARROW_OFFSET = 25
X_SIDE_ARROW_OFFSET = 10
Y_SIDE_ARROW_OFFSET = Y_OFFSET + 10
